// Auth
export const LOGIN = 'LOGIN';
export const FETCH_USER = 'FETCH_USER';

// List Admins
export const FETCH_LIST_ADMINS = 'FETCH_LIST_ADMINS';
export const UPDATE_PAGINATION_LIST_ADMINS = 'UPDATE_PAGINATION_LIST_ADMINS';
export const SHOW_UPDATE_ADMIN_MODEL = 'SHOW_UPDATE_ADMIN_MODEL';
export const HIDE_UPDATE_ADMIN_MODEL = 'HIDE_UPDATE_ADMIN_MODEL';
// List Users
export const FETCH_LIST_USERS = 'FETCH_LIST_USERS';
export const UPDATE_PAGINATION_LIST_USERS = 'UPDATE_PAGINATION_LIST_USERS';
export const SHOW_UPDATE_USER_MODEL = 'SHOW_UPDATE_USER_MODEL';
export const HIDE_UPDATE_USER_MODEL = 'HIDE_UPDATE_USER_MODEL';
//General
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

// List Events
export const FETCH_LIST_EVENTS = 'FETCH_LIST_EVENTS';
export const UPDATE_PAGINATION_LIST_EVENTS = 'UPDATE_PAGINATION_LIST_EVENTS';
export const SHOW_UPDATE_EVENT_MODEL = 'SHOW_UPDATE_EVENT_MODEL';
export const HIDE_UPDATE_EVENT_MODEL = 'HIDE_UPDATE_EVENT_MODEL';
// establishments
export const FETCH_LIST_ESTABLISHMENTS = 'FETCH_LIST_ESTABLISHMENTS';

